#!/bin/bash

echo "=== COMANDOS PARA EJECUTAR EN EL VPS VIA SSH ==="
echo ""

echo "1. PARAR Y LIMPIAR CONTENEDORES EXISTENTES:"
echo "docker compose down -v"
echo ""

echo "2. LIMPIAR IMÁGENES ANTIGAS Y VOLÚMENES (OPCIONAL):"
echo "docker image prune -f"
echo "docker volume prune -f"
echo "docker system prune -f"
echo ""

echo "3. CONSTRUIR Y EJECUTAR CON LOGS:"
echo "docker compose up --build -d"
echo ""

echo "4. VER LOGS EN TIEMPO REAL (TODOS LOS SERVICIOS):"
echo "docker compose logs -f"
echo ""

echo "5. VER LOGS SOLO DE LA APLICACIÓN:"
echo "docker compose logs -f app"
echo ""

echo "6. VER LOGS SOLO DE LA BASE DE DATOS:"
echo "docker compose logs -f database"
echo ""

echo "7. VERIFICAR ESTADO DE LOS CONTENEDORES:"
echo "docker ps"
echo ""

echo "8. ENTRAR AL CONTENEDOR DE LA BASE DE DATOS PARA VERIFICAR:"
echo "docker exec -it cgplayer-db psql -U cgplayer -d cgplayerbd"
echo ""

echo "9. COMANDOS ÚTILES DE BASE DE DATOS:"
echo "# Conectar a PostgreSQL desde el contenedor:"
echo "docker exec -it cgplayer-db psql -U cgplayer -d cgplayerbd"
echo ""
echo "# Ver las tablas:"
echo "\\dt"
echo ""
echo "# Ver usuarios:"
echo "SELECT * FROM \"User\" LIMIT 5;"
echo ""
echo "# Salir de PostgreSQL:"
echo "\\q"
echo ""

echo "10. REINICIAR SOLO LA APLICACIÓN (SIN BORRAR LA BD):"
echo "docker compose restart app"
echo ""

echo "11. VER CREDENCIALES FINALES DE LA BASE DE DATOS:"
echo "Host: 192.99.122.62"
echo "Puerto: 5432"
echo "Base de datos: cgplayerbd"
echo "Usuario: cgplayer"
echo "Contraseña: cgplayerpassword"
echo ""

echo "12. COMANDO PARA BORRAR COMPLETAMENTE LA BD Y RECREARLA:"
echo "docker compose down -v"
echo "docker volume rm cgplayerweb_postgres_data cgplayerweb_redis_data cgplayerweb_app_uploads cgplayerweb_app_logs 2>/dev/null || true"
echo "docker compose up --build -d"
echo ""

echo "13. VERIFICAR CONEXIÓN A LA BD DESDE FUERA:"
echo "# Desde DBeaver o cliente PostgreSQL:"
echo "psql -h 192.99.122.62 -p 5432 -U cgplayer -d cgplayerbd"
echo ""

echo "14. TEST DE CORS Y API:"
echo "curl -X GET http://192.99.122.62:3001/api/health"
echo "curl -X GET http://192.99.122.62:3001/api/network-config"
echo ""

echo "=== CORRECCIONES REALIZADAS ==="
echo "✅ Corregido DATABASE_URL en docker-compose.yml: cgplayerbd con password: cgplayerpassword"
echo "✅ Corregido healthcheck de PostgreSQL para usar cgplayerbd"
echo "✅ Corregido CORS dinámico para usar SERVER_IP y CORS_ORIGINS del entorno"
echo "✅ Variables de entorno consistentes entre archivos"
echo "✅ Sistema de configuración dinámica actualizado para VPS"
echo "✅ Mejorado script de inicialización de Prisma con migraciones robustas"
echo "✅ Agregado script init-backend.sh para mejor manejo de la inicialización"
echo ""

echo "🔧 DEBUGGING:"
echo "Si sigues teniendo problemas, ejecuta:"
echo "docker compose logs -f app | grep -i error"
echo "docker compose logs -f database | grep -i error"
echo "docker compose logs -f app | grep -i cors"
echo "docker compose logs -f app | grep -i prisma"
echo ""
echo "15. COMANDOS DE DEBUGGING ESPECÍFICOS:"
echo "# Ver logs de inicialización:"
echo "docker compose logs app | grep init"
echo ""
echo "# Ejecutar migraciones manualmente:"
echo "docker exec -it cgplayer-app /bin/sh"
echo "cd /app/backend"
echo "npx prisma migrate deploy"
echo ""
echo "# Verificar tablas desde el contenedor:"
echo "docker exec -it cgplayer-db psql -U cgplayer -d cgplayerbd -c '\dt'"
