#!/bin/bash

echo "=== COMANDOS PARA LIMPIAR UPLOADS EN EL VPS VIA SSH ==="
echo ""

echo "🗑️ LIMPIAR CARPETAS DE UPLOADS DEL BACKEND"
echo ""

echo "OPCIÓN 1: DESDE DENTRO DEL CONTENEDOR"
echo "# Entrar al contenedor:"
echo "docker exec -it cgplayer-app /bin/sh"
echo ""
echo "# Una vez dentro del contenedor, ejecutar:"
echo "cd /app/backend/uploads"
echo ""
echo "# Limpiar carpeta songs (conservar carpeta):"
echo "find songs/ -type f -delete"
echo "find songs/ -type d -empty -not -path songs/ -delete"
echo ""
echo "# Limpiar carpeta events (conservar carpeta):"
echo "find events/ -type f -delete"  
echo "find events/ -type d -empty -not -path events/ -delete"
echo ""
echo "# Limpiar subcarpetas de images (conservar .gitkeep):"
echo "find images/playlists/ -type f ! -name '.gitkeep' ! -name 'README.md' -delete"
echo "find images/profiles/ -type f ! -name '.gitkeep' -delete"
echo ""
echo "# Verificar que las carpetas estén vacías:"
echo "ls -la songs/"
echo "ls -la events/"  
echo "ls -la images/playlists/"
echo "ls -la images/profiles/"
echo ""
echo "# Salir del contenedor:"
echo "exit"
echo ""

echo "OPCIÓN 2: COMANDO DIRECTO DESDE SSH (MÁS RÁPIDO)"
echo "# Limpiar songs:"
echo "docker exec cgplayer-app find /app/backend/uploads/songs/ -type f -delete"
echo "docker exec cgplayer-app find /app/backend/uploads/songs/ -type d -empty -not -path '/app/backend/uploads/songs/' -delete"
echo ""
echo "# Limpiar events:"
echo "docker exec cgplayer-app find /app/backend/uploads/events/ -type f -delete"
echo "docker exec cgplayer-app find /app/backend/uploads/events/ -type d -empty -not -path '/app/backend/uploads/events/' -delete"
echo ""
echo "# Limpiar images/playlists (conservar .gitkeep y README.md):"
echo "docker exec cgplayer-app find /app/backend/uploads/images/playlists/ -type f ! -name '.gitkeep' ! -name 'README.md' -delete"
echo ""
echo "# Limpiar images/profiles (conservar .gitkeep):"
echo "docker exec cgplayer-app find /app/backend/uploads/images/profiles/ -type f ! -name '.gitkeep' -delete"
echo ""

echo "OPCIÓN 3: COMANDO TODO EN UNO (SÚPER RÁPIDO)"
echo "docker exec cgplayer-app /bin/sh -c '"
echo "  find /app/backend/uploads/songs/ -type f -delete && "
echo "  find /app/backend/uploads/songs/ -type d -empty -not -path \"/app/backend/uploads/songs/\" -delete && "
echo "  find /app/backend/uploads/events/ -type f -delete && "
echo "  find /app/backend/uploads/events/ -type d -empty -not -path \"/app/backend/uploads/events/\" -delete && "
echo "  find /app/backend/uploads/images/playlists/ -type f ! -name \".gitkeep\" ! -name \"README.md\" -delete && "
echo "  find /app/backend/uploads/images/profiles/ -type f ! -name \".gitkeep\" -delete && "
echo "  echo \"✅ Todas las carpetas de uploads limpiadas\""
echo "'"
echo ""

echo "VERIFICACIÓN POST-LIMPIEZA:"
echo "# Verificar estado de las carpetas:"
echo "docker exec cgplayer-app ls -la /app/backend/uploads/songs/"
echo "docker exec cgplayer-app ls -la /app/backend/uploads/events/"
echo "docker exec cgplayer-app ls -la /app/backend/uploads/images/playlists/"
echo "docker exec cgplayer-app ls-la /app/backend/uploads/images/profiles/"
echo ""

echo "⚠️ IMPORTANTE:"
echo "- Los comandos conservan las carpetas principales: songs/, events/, images/"
echo "- Se conservan los archivos .gitkeep y README.md"
echo "- Se eliminan TODAS las canciones, eventos e imágenes subidas"
echo "- Las carpetas vacías dentro de songs/ y events/ también se eliminan"
echo ""

echo "🔄 REINICIAR APLICACIÓN DESPUÉS DE LIMPIAR (OPCIONAL):"
echo "docker compose restart app"
